In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [29]:
from sklearn.datasets import fetch_openml
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import check_random_state

In [32]:
X, y = fetch_openml('mnist_784', version=1, return_X_y=True, as_frame=False)

In [33]:
train_samples = 5000

In [22]:
random_state = check_random_state(1)
random_state

RandomState(MT19937) at 0x7FE4C08B55A0

In [23]:
permutation = random_state.permutation(X.shape[0])
permutation

array([ 6670, 49567, 50796, ..., 21440, 50057,  5192])

In [24]:
X = X[permutation]
y = y[permutation]
X, y

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array(['5', '3', '3', ..., '8', '0', '6'], dtype=object))

In [27]:
X = X.reshape((X.shape[0], -1))
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_samples, test_size=10000)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)