In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from sklearn.datasets import fetch_openml
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import check_random_state

In [3]:
X, y = fetch_openml('mnist_784', version=1, return_X_y=True, as_frame=False)

In [11]:
random_state = check_random_state(0)
random_state

RandomState(MT19937) at 0x7FE4C087EC00

In [13]:
permutation = random_state.permutation(X.shape[0])
permutation

array([37411, 20000,  4661, ..., 47654, 24116, 45100])

In [15]:
X = X[permutation]
y = y[permutation]
X, y

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array(['2', '5', '0', ..., '9', '7', '1'], dtype=object))

In [17]:
X = X.reshape((X.shape[0], -1))
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])